name: 🐛 Bug Report
description: Report an issue with a template, theme, or integration in Crossbuild UI.
title: "bug: [short description of the issue]"
labels: [bug, needs triage]
assignees:
  - crossbuildui-maintainers
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue! Please fill out the following details to help us resolve it as quickly as possible.

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Where did the issue occur?
      options:
        - Template (default)
        - Template (cbui-free)
        - Template (cbui-pro)
        - Theme (default-theme.ts)
        - Theme (modern-theme.ts)
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Development Environment
      description: Platform and tool versions you're using (Expo, OS, etc.)
      placeholder: |
        Example: Expo SDK 50, Android 13, macOS 14.1
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the Bug
      description: A clear and concise description of what went wrong.
      placeholder: |
        Example: The `Button` component doesn't switch to dark mode in the cbui-pro template.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Help us reproduce the issue by describing the exact steps.
      placeholder: |
        1. Clone the repo and open `/templates/cbui-pro`
        2. Run `npm install` and `npx expo start`
        3. Switch device to dark mode
        4. Observe the button styles
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen instead?
      placeholder: |
        Button should adapt to dark mode and use the theme’s background and foreground tokens.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Logs (Optional)
      description: Attach images or logs if helpful to illustrate the problem.

  - type: input
    id: github-profile
    attributes:
      label: Your GitHub Profile (Optional)
      placeholder: https://github.com/yourusername
